INSERT INTO STATE (ID ,NAME ) VALUES (1, 'Telangana');
INSERT INTO STATE (ID ,NAME ) VALUES (2, 'Tamilnadu');
INSERT INTO CITY (ID ,NAME  ) VALUES (1, 'JAGTIAL');
INSERT INTO CITY (ID ,NAME  ) VALUES (2, 'Thiruvananthapuram');
INSERT INTO CITY (ID ,NAME ) VALUES (3, 'Karimnagar');
